image:
    #- Visual Studio 2013
    - Visual Studio 2015
    - Visual Studio 2017
environment:
    matrix:
        - BUILDER: scons
          WITH_SUBMODULES: 0
        - BUILDER: scons
          WITH_SUBMODULES: 1
        - BUILDER: cmake
          WITH_SUBMODULES: 0
        - BUILDER: cmake
          WITH_SUBMODULES: 1
matrix:
    exclude:
        - image: Visual Studio 2015
          WITH_SUBMODULES: 1
        - image: Visual Studio 2017
          WITH_SUBMODULES: 1
        - BUILDER: cmake
          WITH_SUBMODULES: 1
install:
- ps: >-
    if (-not (Test-Path C:\Python38\Lib\site-packages\scons-3.0.0)){
      Start-FileDownload "https://downloads.sourceforge.net/project/scons/scons/3.0.0/scons-3.0.0.zip" -FileName "scons-3.0.0.zip"
      7z x -y scons-3.0.0.zip
    }
build_script:
- cmd: set PATH=c:\python38;%PATH%
- cmd: copy c:\python38\python.exe c:\python38\python3.exe
- cmd: python3 scons-3.0.0\setup.py install
- cmd: if %WITH_SUBMODULES%==1 git submodule update --init
- cmd: if %BUILDER%==scons scons
#- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
- cmd: if %BUILDER%==cmake cmake . && cmake --build . && ctest -C Debug --output-on-failure
