language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
git:
  submodules: false
env:
  - BUILDER=scons RELEASE=0 WITH_SUBMODULES=0
  - BUILDER=scons RELEASE=0 WITH_SUBMODULES=1
  - BUILDER=scons RELEASE=1 WITH_SUBMODULES=1
  - BUILDER=cmake WITH_SUBMODULES=0
before_install:
  - which scons || brew install scons
before_script:
  - if [ "$WITH_SUBMODULES" == "1" ]; then git submodule update --init; fi
script:
  - if [ "$BUILDER" == "scons" ]; then scons RELEASE=$RELEASE; fi
  - if [ "$BUILDER" == "cmake" ]; then scons external/lib && cmake . && make && ctest -V; fi
sudo: false
