language: cpp
osx_image: xcode11 # at least until travis default osx version works
jobs:
    include:
        - os: linux
          compiler: clang
          env: EXCLUDE_TESTS=1
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: linux
          compiler: clang
          env: WITH_EXTENSIONS=1
        - os: linux
          compiler: clang
          arch: arm64
          env: CTEST_OPTIONS="-E grammar"
        - os: osx
          compiler: clang
        - os: osx
          compiler: clang
          env: WITH_EXTENSIONS=1 CTEST_OPTIONS="-E grammar"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which scons || brew install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which scons || brew install gmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which mcs || brew install mono; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python3-pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sed -i -e '1s/python$/python3/' $(which scons); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which mcs || sudo apt install mono-mcs; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libncurses-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libgmp-dev; fi
before_script:
  - if [ "$WITH_EXTENSIONS" == "1" ]; then git clone https://github.com/ghewgill/neon-module-registry; for a in $(ls neon-module-registry | grep yaml); do python3 tools/helium.py scripts/module-install.neon $(echo $a | sed -e 's/.yaml//'); done; fi
script:
  - cmake .
  - make
  - if [[ "$EXCLUDE_TESTS" != "1" ]]; then ctest $CTEST_OPTIONS --output-on-failure; fi
sudo: false
