language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
git:
  submodules: false
env:
  - BUILDER=scons RELEASE=0 WITH_SUBMODULES=0
  - BUILDER=scons RELEASE=0 WITH_SUBMODULES=1
  - BUILDER=scons RELEASE=1 WITH_SUBMODULES=1
  - BUILDER=cmake WITH_SUBMODULES=0
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which scons || brew install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which mcs || brew install mono; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which scons || sudo apt install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which mcs || sudo apt install mono-mcs; fi
before_script:
  - if [ "$WITH_SUBMODULES" == "1" ]; then git submodule update --init; fi
script:
  - if [ "$BUILDER" == "scons" ]; then scons RELEASE=$RELEASE; fi
  - if [ "$BUILDER" == "cmake" ]; then scons external/lib && cmake . && make && ctest -V; fi
sudo: false
