language: cpp
os:
  - windows
git:
  submodules: false
env:
  #- BUILDER=scons RELEASE=0 WITH_SUBMODULES=0
  #- BUILDER=scons RELEASE=0 WITH_SUBMODULES=1
  #- BUILDER=scons RELEASE=1 WITH_SUBMODULES=1
  - BUILDER=cmake WITH_SUBMODULES=0
before_install:
  - choco install python2 --params '"/InstallDir:C:\python27\"'
before_script:
  - if [ "$WITH_SUBMODULES" == "1" ]; then git submodule update --init; fi
script:
  - python -c 'print(\"Hello Travis, from path!\");'
  - C:\python27\python -c 'print(\"Hello Travis, from my home dir, of c:\\python27!\");'
  - cmake .
  - make
  - ctest
sudo: false
