language: cpp
os:
  - linux
  - osx
osx_image: xcode6.4
compiler:
  - gcc
  # It seems that the clang compiler on travis doesn't correctly build its own headers.
  #- clang
env:
  - RELEASE=0
  - RELEASE=1
before_install:
  - which scons || brew install scons
script: scons MINIMAL=$MINIMAL RELEASE=$RELEASE
sudo: false
