language: cpp
osx_image: xcode11 # at least until travis default osx version works
jobs:
    include:
        - os: linux
          compiler: clang
          env: EXCLUDE_TESTS=1
        - os: linux
          compiler: gcc
          env: WITH_SUBMODULES=0
        - os: linux
          compiler: clang
          env: WITH_SUBMODULES=0
        - os: linux
          compiler: clang
          env: WITH_SUBMODULES=1
        - os: linux
          compiler: clang
          arch: arm64
          env: WITH_SUBMODULES=0
          env: CTEST_OPTIONS="-E grammar"
        # Currently resid does not build on arm.
        #- os: linux
        #  compiler: clang
        #  arch: arm64
        #  env: RELEASE=0 WITH_SUBMODULES=1 BID_GENERIC=1
        - os: osx
          compiler: clang
          env: WITH_SUBMODULES=0
        - os: osx
          compiler: clang
          env: WITH_SUBMODULES=1
git:
  submodules: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which scons || brew install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which scons || brew install gmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which mcs || brew install mono; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install python3-pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip3 install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo sed -i -e '1s/python$/python3/' $(which scons); fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then which mcs || sudo apt install mono-mcs; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libncurses-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt install libgmp-dev; fi
before_script:
  - if [ "$WITH_SUBMODULES" == "1" ]; then git submodule update --init; fi
script:
  - cmake .
  - make
  - if [[ "$EXCLUDE_TESTS" != "1" ]]; then ctest $CTEST_OPTIONS --output-on-failure; fi
sudo: false
