language: cpp
os:
  - windows
git:
  submodules: false
env:
  #- BUILDER=scons RELEASE=0 WITH_SUBMODULES=0
  #- BUILDER=scons RELEASE=0 WITH_SUBMODULES=1
  #- BUILDER=scons RELEASE=1 WITH_SUBMODULES=1
  - BUILDER=cmake WITH_SUBMODULES=0
before_install:
  - choco install python2 --params '"/InstallDir:C:\\py\\"'
before_script:
  - if [ "$WITH_SUBMODULES" == "1" ]; then git submodule update --init; fi
script:
  - py -c 'print(\"Hello Travis, from path!\");'
  - 'py -c 'print(\"Hello Travis, from path!\");''
  - C:\py\python -c 'print(\"Hello Travis, from my home dir, of c:\\py!\");'
  - python -V
  - 'C:\py\python -v'
  - cmake .
  - make
  - ctest
sudo: false
